# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9497745e3ea48642c461352b56da407ce9d5811020c646fb12e84f267ed57aaa7ae0366a3f9fdb5eb1e372a79d66e334c8b6985ce41dac2ec477d66970890e16

test:
  secret_key_base: a4016450a869d1c665d7a48ca7072e8ceab829c3d28a704f3dd742db0931a355c9d4898bbfbd894b5245851930b3066836b38ff4a8e408612921c60f4bdbcfef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
